Imports des librairies

In [38]:
import pandas as pd

Première analyse des fichiers

In [40]:
import pandas as pd

# Dossier contenant les fichiers CSV
dossier = 'data/'

# Liste des années à vérifier
annees = list(range(2005, 2023))

# Liste des types de fichiers à lire
types_fichiers = ['caracteristiques', 'lieux', 'usagers', 'vehicules', 'vehicules-immatricules-baac']

# Initialisation de la liste pour stocker les résultats d'analyse
resultats_analyse = []

# Fonction pour lire les fichiers et extraire les informations
def analyser_fichier(chemin_fichier, type_fichier, annee):
    separateurs = [',', ';', '\t']
    for sep in separateurs:
        try:
            df = pd.read_csv(chemin_fichier, encoding='ISO-8859-1', delimiter=sep, on_bad_lines='skip')
            if len(df.columns) > 1:
                return {
                    'nom_fichier': f'{type_fichier}_{annee}.csv',
                    'chemin_fichier_complet': chemin_fichier,
                    'nombre_colonnes': len(df.columns),
                    'nombre_lignes': len(df),
                    'colonnes': df.columns.tolist(),
                    'statut': 'Succès',
                    'separateur': sep
                }
        except Exception:
            continue
    return {
        'nom_fichier': f'{type_fichier}_{annee}.csv',
        'chemin_fichier_complet': chemin_fichier,
        'nombre_colonnes': 1,
        'nombre_lignes': 0,
        'colonnes': [],
        'statut': 'Échec de lecture',
        'separateur': 'N/A'
    }

# Analyse des fichiers et stockage des résultats
for type_fichier in types_fichiers:
    for annee in annees:
        chemin_fichier = f'{dossier}{type_fichier}_{annee}.csv'
        resultat = analyser_fichier(chemin_fichier, type_fichier, annee)
        resultat['type_fichier'] = type_fichier
        resultat['annee'] = annee
        resultats_analyse.append(resultat)

# Création d'un DataFrame pour les résultats d'analyse
analyse_df = pd.DataFrame(resultats_analyse)

# Export des résultats d'analyse en fichier Excel
# with pd.ExcelWriter('resultats_analyse.xlsx') as writer:
#    analyse_df.to_excel(writer, sheet_name='Résultats Analyse', index=False)

print("Export terminé.")

/var/folders/js/wtxbjqtd4hl50l7w9xmf2ymm0000gn/T/ipykernel_39654/1708688783.py:20: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(chemin_fichier, encoding='ISO-8859-1', delimiter=sep, on_bad_lines='skip')
/var/folders/js/wtxbjqtd4hl50l7w9xmf2ymm0000gn/T/ipykernel_39654/1708688783.py:20: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(chemin_fichier, encoding='ISO-8859-1', delimiter=sep, on_bad_lines='skip')
/var/folders/js/wtxbjqtd4hl50l7w9xmf2ymm0000gn/T/ipykernel_39654/1708688783.py:20: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(chemin_fichier, encoding='ISO-8859-1', delimiter=sep, on_bad_lines='skip')
/var/folders/js/wtxbjqtd4hl50l7w9xmf2ymm0000gn/T/ipykernel_39654/1708688783.py:20: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(chemin_fichier, encoding='ISO-8859-1', delimiter=sep, on_bad_lines='skip')
/var/folders/js/wtxbjqtd4hl50l7w9xmf2ymm0000gn/T/ipykernel_39654/1708688783.py:20: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(chemin_fichier, encoding='ISO-8859-1', delimiter=sep, on_bad_lines='skip')

Export terminé.

In [48]:
analyse_df.tail()

,nom_fichier,chemin_fichier_complet,nombre_colonnes,nombre_lignes,colonnes,statut,separateur,type_fichier,annee
85,vehicules-immatricules-baac_2018.csv,data/vehicules-immatricules-baac_2018.csv,8,94584,"[Id_accident, Lettre Conventionnelle VÃ©hicule...",Succès,;,vehicules-immatricules-baac,2018
86,vehicules-immatricules-baac_2019.csv,data/vehicules-immatricules-baac_2019.csv,8,94674,"[Id_accident, Lettre Conventionnelle VÃ©hicule...",Succès,;,vehicules-immatricules-baac,2019
87,vehicules-immatricules-baac_2020.csv,data/vehicules-immatricules-baac_2020.csv,8,74664,"[Id_accident, Lettre Conventionnelle VÃ©hicule...",Succès,;,vehicules-immatricules-baac,2020
88,vehicules-immatricules-baac_2021.csv,data/vehicules-immatricules-baac_2021.csv,8,89416,"[Id_accident, Lettre Conventionnelle VÃ©hicule...",Succès,;,vehicules-immatricules-baac,2021
89,vehicules-immatricules-baac_2022.csv,data/vehicules-immatricules-baac_2022.csv,1,0,[],Échec de lecture,N/A,vehicules-immatricules-baac,2022

Analyse des colonnes

In [52]:
# Initialisation du DataFrame final
informations_colonnes = []

# Filtrer le DataFrame pour ne conserver que les lignes où le statut est "Succès"
analyse_df_succes = analyse_df[analyse_df['statut'] == 'Succès']

# Parcourir chaque fichier dans le DataFrame filtré
for idx, row in analyse_df_succes.iterrows():
    chemin_fichier = row['chemin_fichier_complet']
    type_fichier = row['type_fichier']
    separateur = row['separateur']
    
    # Charger le fichier CSV
    try:
        df = pd.read_csv(chemin_fichier, sep=separateur, encoding='ISO-8859-1')
        
        # Obtenir les informations sur les colonnes
        for col in df.columns:
            info_col = {
                'chemin_fichier_complet': chemin_fichier,
                'type_fichier': type_fichier,
                'nom_colonne': col,
                'nombre_lignes': len(df),
                'taux_na': df[col].isna().mean(),
                'format': df[col].dtype
            }
            informations_colonnes.append(info_col)
    except Exception as e:
        print(f"Erreur lors de la lecture du fichier {chemin_fichier} : {e}")

# Créer le DataFrame final
analyse_colonnes_df = pd.DataFrame(informations_colonnes)

analyse_colonnes_df.head()

/var/folders/js/wtxbjqtd4hl50l7w9xmf2ymm0000gn/T/ipykernel_39654/1284557679.py:15: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(chemin_fichier, sep=separateur, encoding='ISO-8859-1')
/var/folders/js/wtxbjqtd4hl50l7w9xmf2ymm0000gn/T/ipykernel_39654/1284557679.py:15: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(chemin_fichier, sep=separateur, encoding='ISO-8859-1')
/var/folders/js/wtxbjqtd4hl50l7w9xmf2ymm0000gn/T/ipykernel_39654/1284557679.py:15: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(chemin_fichier, sep=separateur, encoding='ISO-8859-1')
/var/folders/js/wtxbjqtd4hl50l7w9xmf2ymm0000gn/T/ipykernel_39654/1284557679.py:15: DtypeWarning: Columns (6) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(chemin_fichier, sep=separateur, encoding='ISO-8859-1')
/var/folders/js/wtxbjqtd4hl50l7w9xmf2ymm0000gn/T/ipykernel_39654/1284557679.py:15: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(chemin_fichier, sep=separateur, encoding='ISO-8859-1')

,chemin_fichier_complet,type_fichier,nom_colonne,nombre_lignes,taux_na,format
0,data/caracteristiques_2005.csv,caracteristiques,Num_Acc,87026,0.0,int64
1,data/caracteristiques_2005.csv,caracteristiques,an,87026,0.0,int64
2,data/caracteristiques_2005.csv,caracteristiques,mois,87026,0.0,int64
3,data/caracteristiques_2005.csv,caracteristiques,jour,87026,0.0,int64
4,data/caracteristiques_2005.csv,caracteristiques,hrmn,87026,0.0,int64

In [59]:
analyse_colonnes_df.info

<bound method DataFrame.info of                          chemin_fichier_complet                 type_fichier  \
0                data/caracteristiques_2005.csv             caracteristiques
1                data/caracteristiques_2005.csv             caracteristiques
2                data/caracteristiques_2005.csv             caracteristiques
3                data/caracteristiques_2005.csv             caracteristiques
4                data/caracteristiques_2005.csv             caracteristiques
...                                         ...                          ...
1107  data/vehicules-immatricules-baac_2021.csv  vehicules-immatricules-baac
1108  data/vehicules-immatricules-baac_2021.csv  vehicules-immatricules-baac
1109  data/vehicules-immatricules-baac_2021.csv  vehicules-immatricules-baac
1110  data/vehicules-immatricules-baac_2021.csv  vehicules-immatricules-baac
1111  data/vehicules-immatricules-baac_2021.csv  vehicules-immatricules-baac

                             nom_colonne  nombre_lignes   taux_na   format
0                                Num_Acc          87026  0.000000    int64
1                                     an          87026  0.000000    int64
2                                   mois          87026  0.000000    int64
3                                   jour          87026  0.000000    int64
4                                   hrmn          87026  0.000000    int64
...                                  ...            ...       ...      ...
1107  Lieu Admin Actuel - Territoire Nom          89416  0.000000   object
1108      Type Accident - LibellÃ© (old)          89416  0.000000   object
1109                                CNIT          89416  0.217288   object
1110                CatÃ©gorie vÃ©hicule          89416  0.000000   object
1111                       Age vÃ©hicule          89416  0.054901  float64

[1112 rows x 6 columns]>

In [71]:
fusion_df = analyse_colonnes_df.groupby(['type_fichier', 'nom_colonne'], as_index=False).agg({'nombre_lignes': 'sum'})
fusion_df.head()

       type_fichier  nom_colonne  nombre_lignes
0  caracteristiques  Accident_Id          55302
1  caracteristiques      Num_Acc        1121571
2  caracteristiques          adr        1176873
3  caracteristiques          agg        1176873
4  caracteristiques           an        1176873